
package weather;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CRM_VIP_Proxy", targetNamespace = "http://www.tech-trans.com.cn/", wsdlLocation = "http://114.255.150.14:1030/CRM_VIP_Proxy.asmx?wsdl")
public class CRMVIPProxy
    extends Service
{

    private final static URL CRMVIPPROXY_WSDL_LOCATION;
    private final static WebServiceException CRMVIPPROXY_EXCEPTION;
    private final static QName CRMVIPPROXY_QNAME = new QName("http://www.tech-trans.com.cn/", "CRM_VIP_Proxy");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://114.255.150.14:1030/CRM_VIP_Proxy.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRMVIPPROXY_WSDL_LOCATION = url;
        CRMVIPPROXY_EXCEPTION = e;
    }

    public CRMVIPProxy() {
        super(__getWsdlLocation(), CRMVIPPROXY_QNAME);
    }

    public CRMVIPProxy(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRMVIPPROXY_QNAME, features);
    }

    public CRMVIPProxy(URL wsdlLocation) {
        super(wsdlLocation, CRMVIPPROXY_QNAME);
    }

    public CRMVIPProxy(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRMVIPPROXY_QNAME, features);
    }

    public CRMVIPProxy(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRMVIPProxy(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CRMVIPProxySoap
     */
    @WebEndpoint(name = "CRM_VIP_ProxySoap")
    public CRMVIPProxySoap getCRMVIPProxySoap() {
        return super.getPort(new QName("http://www.tech-trans.com.cn/", "CRM_VIP_ProxySoap"), CRMVIPProxySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMVIPProxySoap
     */
    @WebEndpoint(name = "CRM_VIP_ProxySoap")
    public CRMVIPProxySoap getCRMVIPProxySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tech-trans.com.cn/", "CRM_VIP_ProxySoap"), CRMVIPProxySoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CRMVIPProxySoap
     */
    @WebEndpoint(name = "CRM_VIP_ProxySoap12")
    public CRMVIPProxySoap getCRMVIPProxySoap12() {
        return super.getPort(new QName("http://www.tech-trans.com.cn/", "CRM_VIP_ProxySoap12"), CRMVIPProxySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRMVIPProxySoap
     */
    @WebEndpoint(name = "CRM_VIP_ProxySoap12")
    public CRMVIPProxySoap getCRMVIPProxySoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tech-trans.com.cn/", "CRM_VIP_ProxySoap12"), CRMVIPProxySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRMVIPPROXY_EXCEPTION!= null) {
            throw CRMVIPPROXY_EXCEPTION;
        }
        return CRMVIPPROXY_WSDL_LOCATION;
    }

}
