
package weather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRM_VIP_ProxySoap", targetNamespace = "http://www.tech-trans.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRMVIPProxySoap {


    /**
     * 
     * @param method
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Proxy", action = "http://www.tech-trans.com.cn/Proxy")
    @WebResult(name = "ProxyResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "Proxy", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.Proxy")
    @ResponseWrapper(localName = "ProxyResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.ProxyResponse")
    public String proxy(
        @WebParam(name = "method", targetNamespace = "http://www.tech-trans.com.cn/")
        String method,
        @WebParam(name = "data", targetNamespace = "http://www.tech-trans.com.cn/")
        String data);

    /**
     * 手机号获取会员等级
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfBaseVipInfo
     */
    @WebMethod(operationName = "GetVipBaseInfoByMobile", action = "http://www.tech-trans.com.cn/GetVipBaseInfoByMobile")
    @WebResult(name = "GetVipBaseInfoByMobileResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetVipBaseInfoByMobile", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipBaseInfoByMobile")
    @ResponseWrapper(localName = "GetVipBaseInfoByMobileResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipBaseInfoByMobileResponse")
    public ResponseDataOfBaseVipInfo getVipBaseInfoByMobile(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfBaseVipInfoRequest request);

    /**
     * 会员资产支付
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfString
     */
    @WebMethod(operationName = "CRMPay", action = "http://www.tech-trans.com.cn/CRMPay")
    @WebResult(name = "CRMPayResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "CRMPay", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMPay")
    @ResponseWrapper(localName = "CRMPayResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMPayResponse")
    public ResponseDataOfString crmPay(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfCRMPayRequest request);

    /**
     * 会员资产退款
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfString
     */
    @WebMethod(operationName = "CRMRefund", action = "http://www.tech-trans.com.cn/CRMRefund")
    @WebResult(name = "CRMRefundResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "CRMRefund", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMRefund")
    @ResponseWrapper(localName = "CRMRefundResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMRefundResponse")
    public ResponseDataOfString crmRefund(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfCRMRefundRequest request);

    /**
     * 查询会员资产支付记录
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfArrayOfCRMPayLedger
     */
    @WebMethod(operationName = "CRMPayLedgerQuery", action = "http://www.tech-trans.com.cn/CRMPayLedgerQuery")
    @WebResult(name = "CRMPayLedgerQueryResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "CRMPayLedgerQuery", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMPayLedgerQuery")
    @ResponseWrapper(localName = "CRMPayLedgerQueryResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMPayLedgerQueryResponse")
    public ResponseDataOfArrayOfCRMPayLedger crmPayLedgerQuery(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfCRMPayLedgerQueryRequest request);

    /**
     * 开卡
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfCreateVip
     */
    @WebMethod(operationName = "VipCreate", action = "http://www.tech-trans.com.cn/VipCreate")
    @WebResult(name = "VipCreateResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "VipCreate", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.VipCreate")
    @ResponseWrapper(localName = "VipCreateResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.VipCreateResponse")
    public ResponseDataOfCreateVip vipCreate(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfCreateVipRequest request);

    /**
     * 修改会员资料
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfEmptyResponeData
     */
    @WebMethod(operationName = "VipModify", action = "http://www.tech-trans.com.cn/VipModify")
    @WebResult(name = "VipModifyResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "VipModify", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.VipModify")
    @ResponseWrapper(localName = "VipModifyResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.VipModifyResponse")
    public ResponseDataOfEmptyResponeData vipModify(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfVipModifyRequest request);

    /**
     * 获取礼品库存
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfGiftListInfo
     */
    @WebMethod(operationName = "GetGiftList", action = "http://www.tech-trans.com.cn/GetGiftList")
    @WebResult(name = "GetGiftListResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetGiftList", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetGiftList")
    @ResponseWrapper(localName = "GetGiftListResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetGiftListResponse")
    public ResponseDataOfGiftListInfo getGiftList(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfGiftListInfoRequest request);

    /**
     * 获取礼品库存（调入调出使用）
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfGiftListInfo
     */
    @WebMethod(operationName = "QueryQOH", action = "http://www.tech-trans.com.cn/QueryQOH")
    @WebResult(name = "QueryQOHResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "QueryQOH", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.QueryQOH")
    @ResponseWrapper(localName = "QueryQOHResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.QueryQOHResponse")
    public ResponseDataOfGiftListInfo queryQOH(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfGiftListInfoRequest request);

    /**
     * 礼品兑换
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfGiftExchangeInfo
     */
    @WebMethod(operationName = "GiftUseh", action = "http://www.tech-trans.com.cn/GiftUseh")
    @WebResult(name = "GiftUsehResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GiftUseh", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GiftUseh")
    @ResponseWrapper(localName = "GiftUsehResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GiftUsehResponse")
    public ResponseDataOfGiftExchangeInfo giftUseh(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfGiftExchangeInfoRequest request);

    /**
     * 会员礼品兑换记录
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfArrayOfExchangeGiftRecord
     */
    @WebMethod(operationName = "GetExchangeGiftRecord", action = "http://www.tech-trans.com.cn/GetExchangeGiftRecord")
    @WebResult(name = "GetExchangeGiftRecordResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetExchangeGiftRecord", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetExchangeGiftRecord")
    @ResponseWrapper(localName = "GetExchangeGiftRecordResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetExchangeGiftRecordResponse")
    public ResponseDataOfArrayOfExchangeGiftRecord getExchangeGiftRecord(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfExchangeGiftRecordRequest request);

    /**
     * 会员消费记录
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfListOfxfTranssalestotal
     */
    @WebMethod(operationName = "GetVipSalesRecord", action = "http://www.tech-trans.com.cn/GetVipSalesRecord")
    @WebResult(name = "GetVipSalesRecordResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetVipSalesRecord", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipSalesRecord")
    @ResponseWrapper(localName = "GetVipSalesRecordResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipSalesRecordResponse")
    public ResponseDataOfListOfxfTranssalestotal getVipSalesRecord(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfVipSalesRecordRequest request);

    /**
     * 会员积分记录
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfArrayOfxfBonusledger
     */
    @WebMethod(operationName = "GetBonusledgerRecord", action = "http://www.tech-trans.com.cn/GetBonusledgerRecord")
    @WebResult(name = "GetBonusledgerRecordResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetBonusledgerRecord", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetBonusledgerRecord")
    @ResponseWrapper(localName = "GetBonusledgerRecordResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetBonusledgerRecordResponse")
    public ResponseDataOfArrayOfxfBonusledger getBonusledgerRecord(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfBonusledgerRecordRequest request);

    /**
     * 销售
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfBonusInfo
     */
    @WebMethod(operationName = "Consume", action = "http://www.tech-trans.com.cn/Consume")
    @WebResult(name = "ConsumeResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "Consume", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.Consume")
    @ResponseWrapper(localName = "ConsumeResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.ConsumeResponse")
    public ResponseDataOfBonusInfo consume(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfConsumeRequest request);

    /**
     * 检测销售，算分
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfBonusInfo
     */
    @WebMethod(operationName = "CheckConsume", action = "http://www.tech-trans.com.cn/CheckConsume")
    @WebResult(name = "CheckConsumeResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "CheckConsume", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CheckConsume")
    @ResponseWrapper(localName = "CheckConsumeResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CheckConsumeResponse")
    public ResponseDataOfBonusInfo checkConsume(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfConsumeRequest request);

    /**
     * 获取vip 信息折扣
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfListOfVIP
     */
    @WebMethod(operationName = "GetVipDis", action = "http://www.tech-trans.com.cn/GetVipDis")
    @WebResult(name = "GetVipDisResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetVipDis", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipDis")
    @ResponseWrapper(localName = "GetVipDisResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipDisResponse")
    public ResponseDataOfListOfVIP getVipDis(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfVipDisRequest request);

    /**
     * 获取vip信息
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfListOfVIP
     */
    @WebMethod(operationName = "GetVipInfo", action = "http://www.tech-trans.com.cn/GetVipInfo")
    @WebResult(name = "GetVipInfoResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetVipInfo", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipInfo")
    @ResponseWrapper(localName = "GetVipInfoResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipInfoResponse")
    public ResponseDataOfListOfVIP getVipInfo(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfVipInfoRequest request);

    /**
     * 获取会员注册基本信息
     * 
     * @return
     *     returns weather.ResponseDataOfBasicInfo
     */
    @WebMethod(operationName = "GetBasicInfo", action = "http://www.tech-trans.com.cn/GetBasicInfo")
    @WebResult(name = "GetBasicInfoResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetBasicInfo", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetBasicInfo")
    @ResponseWrapper(localName = "GetBasicInfoResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetBasicInfoResponse")
    public ResponseDataOfBasicInfo getBasicInfo();

    /**
     * 返回等级列表
     * 
     * @return
     *     returns weather.ResponseDataOfGradeInfo
     */
    @WebMethod(operationName = "GetGradeList", action = "http://www.tech-trans.com.cn/GetGradeList")
    @WebResult(name = "GetGradeListResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetGradeList", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetGradeList")
    @ResponseWrapper(localName = "GetGradeListResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetGradeListResponse")
    public ResponseDataOfGradeInfo getGradeList();

    /**
     * 积分补录
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfBonusInfo
     */
    @WebMethod(operationName = "RepairConsume", action = "http://www.tech-trans.com.cn/RepairConsume")
    @WebResult(name = "RepairConsumeResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "RepairConsume", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.RepairConsume")
    @ResponseWrapper(localName = "RepairConsumeResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.RepairConsumeResponse")
    public ResponseDataOfBonusInfo repairConsume(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfRepairConsumeRequest request);

    /**
     * 查询发给该店的转出单
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfTOresult
     */
    @WebMethod(operationName = "QueryTO", action = "http://www.tech-trans.com.cn/QueryTO")
    @WebResult(name = "QueryTOResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "QueryTO", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.QueryTO")
    @ResponseWrapper(localName = "QueryTOResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.QueryTOResponse")
    public ResponseDataOfTOresult queryTO(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfQueryTORequest request);

    /**
     * 确认调入
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfFirmTIresult
     */
    @WebMethod(operationName = "ConfrimTI", action = "http://www.tech-trans.com.cn/ConfrimTI")
    @WebResult(name = "ConfrimTIResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "ConfrimTI", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.ConfrimTI")
    @ResponseWrapper(localName = "ConfrimTIResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.ConfrimTIResponse")
    public ResponseDataOfFirmTIresult confrimTI(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfConfrimTIRequest request);

    /**
     * 礼品调出单创建
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfTOresult
     */
    @WebMethod(operationName = "CreateTO", action = "http://www.tech-trans.com.cn/CreateTO")
    @WebResult(name = "CreateTOResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "CreateTO", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CreateTO")
    @ResponseWrapper(localName = "CreateTOResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CreateTOResponse")
    public ResponseDataOfTOresult createTO(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfCreateTORequest request);

    /**
     * 绑定微信ID
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfEmptyResponeData
     */
    @WebMethod(operationName = "BindOpenID", action = "http://www.tech-trans.com.cn/BindOpenID")
    @WebResult(name = "BindOpenIDResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "BindOpenID", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.BindOpenID")
    @ResponseWrapper(localName = "BindOpenIDResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.BindOpenIDResponse")
    public ResponseDataOfEmptyResponeData bindOpenID(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfBindOpenIDRequest request);

    /**
     * 通过vipcode 手机号 openid 查会员信息
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfListOfVIP
     */
    @WebMethod(operationName = "GetVipInfoByMobileOpenID", action = "http://www.tech-trans.com.cn/GetVipInfoByMobileOpenID")
    @WebResult(name = "GetVipInfoByMobileOpenIDResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetVipInfoByMobileOpenID", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipInfoByMobileOpenID")
    @ResponseWrapper(localName = "GetVipInfoByMobileOpenIDResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipInfoByMobileOpenIDResponse")
    public ResponseDataOfListOfVIP getVipInfoByMobileOpenID(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfBindOpenIDRequest request);

    /**
     * 通过code获取Info信息
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfListOfEBINFORMATION
     */
    @WebMethod(operationName = "GetInformation", action = "http://www.tech-trans.com.cn/GetInformation")
    @WebResult(name = "GetInformationResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetInformation", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetInformation")
    @ResponseWrapper(localName = "GetInformationResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetInformationResponse")
    public ResponseDataOfListOfEBINFORMATION getInformation(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfInformationRequest request);

    /**
     * 通过node获取children和info信息
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfNodeInfo
     */
    @WebMethod(operationName = "GetNodeInfo", action = "http://www.tech-trans.com.cn/GetNodeInfo")
    @WebResult(name = "GetNodeInfoResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetNodeInfo", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetNodeInfo")
    @ResponseWrapper(localName = "GetNodeInfoResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetNodeInfoResponse")
    public ResponseDataOfNodeInfo getNodeInfo(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfNodeInfoRequest request);

    /**
     * 积分调整
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfBonusInfo
     */
    @WebMethod(operationName = "BonusChange", action = "http://www.tech-trans.com.cn/BonusChange")
    @WebResult(name = "BonusChangeResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "BonusChange", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.BonusChange")
    @ResponseWrapper(localName = "BonusChangeResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.BonusChangeResponse")
    public ResponseDataOfBonusInfo bonusChange(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfBonusChangeRequest request);

    /**
     * 活动报名
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfBonusInfo
     */
    @WebMethod(operationName = "ActivitEnroll", action = "http://www.tech-trans.com.cn/ActivitEnroll")
    @WebResult(name = "ActivitEnrollResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "ActivitEnroll", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.ActivitEnroll")
    @ResponseWrapper(localName = "ActivitEnrollResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.ActivitEnrollResponse")
    public ResponseDataOfBonusInfo activitEnroll(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfActivitEnrollRequest request);

    /**
     * 活动查询
     * 
     * @return
     *     returns weather.ResponseDataOfListOfCRMMEMBERMSG
     */
    @WebMethod(operationName = "QueryActivit", action = "http://www.tech-trans.com.cn/QueryActivit")
    @WebResult(name = "QueryActivitResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "QueryActivit", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.QueryActivit")
    @ResponseWrapper(localName = "QueryActivitResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.QueryActivitResponse")
    public ResponseDataOfListOfCRMMEMBERMSG queryActivit();

    /**
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfBoolean
     */
    @WebMethod(operationName = "SendSMS", action = "http://www.tech-trans.com.cn/SendSMS")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.SendSMSResponse")
    public ResponseDataOfBoolean sendSMS(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfSMSRequest request);

    /**
     * 退货检测
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfCheckReturnGoodRespose
     */
    @WebMethod(operationName = "CheckReturnGood", action = "http://www.tech-trans.com.cn/CheckReturnGood")
    @WebResult(name = "CheckReturnGoodResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "CheckReturnGood", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CheckReturnGood")
    @ResponseWrapper(localName = "CheckReturnGoodResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CheckReturnGoodResponse")
    public ResponseDataOfCheckReturnGoodRespose checkReturnGood(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfCheckReturnGoodRequest request);

    /**
     * 获取会员消费总金额，次数
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfVipSales
     */
    @WebMethod(operationName = "GetVipSalse", action = "http://www.tech-trans.com.cn/GetVipSalse")
    @WebResult(name = "GetVipSalseResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetVipSalse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipSalse")
    @ResponseWrapper(localName = "GetVipSalseResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetVipSalseResponse")
    public ResponseDataOfVipSales getVipSalse(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfString request);

    /**
     * 销售（二维码补录积分）（不加密）
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfBonusInfo
     */
    @WebMethod(operationName = "Consume_QRcode_NoEncrypt", action = "http://www.tech-trans.com.cn/Consume_QRcode_NoEncrypt")
    @WebResult(name = "Consume_QRcode_NoEncryptResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "Consume_QRcode_NoEncrypt", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.ConsumeQRcodeNoEncrypt")
    @ResponseWrapper(localName = "Consume_QRcode_NoEncryptResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.ConsumeQRcodeNoEncryptResponse")
    public ResponseDataOfBonusInfo consumeQRcodeNoEncrypt(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfConsumeQRcodeNoEncryptRequest request);

    /**
     * 检验用户名密码
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfBoolean
     */
    @WebMethod(operationName = "CheckVIP_Password", action = "http://www.tech-trans.com.cn/CheckVIP_Password")
    @WebResult(name = "CheckVIP_PasswordResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "CheckVIP_Password", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CheckVIPPassword")
    @ResponseWrapper(localName = "CheckVIP_PasswordResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CheckVIPPasswordResponse")
    public ResponseDataOfBoolean checkVIPPassword(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfCheckVIPPasswordRequest request);

    /**
     * 查询该会员当前可用的电子券(POS用)
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfListOfCRMTender
     */
    @WebMethod(operationName = "GetCRMTicker", action = "http://www.tech-trans.com.cn/GetCRMTicker")
    @WebResult(name = "GetCRMTickerResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetCRMTicker", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetCRMTicker")
    @ResponseWrapper(localName = "GetCRMTickerResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetCRMTickerResponse")
    public ResponseDataOfListOfCRMTender getCRMTicker(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfGetCRMTickerRequest request);

    /**
     * 核销电子券(POS用)
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfCRMTenderReturn
     */
    @WebMethod(operationName = "CRMTicketPay", action = "http://www.tech-trans.com.cn/CRMTicketPay")
    @WebResult(name = "CRMTicketPayResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "CRMTicketPay", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMTicketPay")
    @ResponseWrapper(localName = "CRMTicketPayResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMTicketPayResponse")
    public ResponseDataOfCRMTenderReturn crmTicketPay(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfCRMTicketPayRequest request);

    /**
     * 领取电子券
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfTicketType
     */
    @WebMethod(operationName = "GetTicketByTypeCode", action = "http://www.tech-trans.com.cn/GetTicketByTypeCode")
    @WebResult(name = "GetTicketByTypeCodeResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetTicketByTypeCode", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetTicketByTypeCode")
    @ResponseWrapper(localName = "GetTicketByTypeCodeResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetTicketByTypeCodeResponse")
    public ResponseDataOfTicketType getTicketByTypeCode(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfTicketRequest request);

    /**
     * 使用电子券
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfCRMTickReturn
     */
    @WebMethod(operationName = "UseCRMTicket", action = "http://www.tech-trans.com.cn/UseCRMTicket")
    @WebResult(name = "UseCRMTicketResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "UseCRMTicket", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.UseCRMTicket")
    @ResponseWrapper(localName = "UseCRMTicketResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.UseCRMTicketResponse")
    public ResponseDataOfCRMTickReturn useCRMTicket(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfTicketRequest request);

    /**
     * 查询电子券类型
     * 
     * @return
     *     returns weather.ResponseDataOfListOfTicketType
     */
    @WebMethod(operationName = "QueryTicketType", action = "http://www.tech-trans.com.cn/QueryTicketType")
    @WebResult(name = "QueryTicketTypeResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "QueryTicketType", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.QueryTicketType")
    @ResponseWrapper(localName = "QueryTicketTypeResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.QueryTicketTypeResponse")
    public ResponseDataOfListOfTicketType queryTicketType();

    /**
     * 获取电子券状态
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfListOfCRMTICKET
     */
    @WebMethod(operationName = "GetUsedTicket", action = "http://www.tech-trans.com.cn/GetUsedTicket")
    @WebResult(name = "GetUsedTicketResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "GetUsedTicket", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetUsedTicket")
    @ResponseWrapper(localName = "GetUsedTicketResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.GetUsedTicketResponse")
    public ResponseDataOfListOfCRMTICKET getUsedTicket(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfString request);

    /**
     * 获取会员可用资产
     * 
     * @param request
     * @return
     *     returns weather.ResponseDataOfListOfCRMTender
     */
    @WebMethod(operationName = "CRMPayTenderQuery", action = "http://www.tech-trans.com.cn/CRMPayTenderQuery")
    @WebResult(name = "CRMPayTenderQueryResult", targetNamespace = "http://www.tech-trans.com.cn/")
    @RequestWrapper(localName = "CRMPayTenderQuery", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMPayTenderQuery")
    @ResponseWrapper(localName = "CRMPayTenderQueryResponse", targetNamespace = "http://www.tech-trans.com.cn/", className = "weather.CRMPayTenderQueryResponse")
    public ResponseDataOfListOfCRMTender crmPayTenderQuery(
        @WebParam(name = "request", targetNamespace = "http://www.tech-trans.com.cn/")
        RequestDataOfCRMPayTenderRequest request);

}
